### ISSUE TITLE
Sayori and Natsuki hugs

### ISSUE THREAD

**Issue by sayuri3** [sayuri3/dokis#54]
Hugging Sayori or Natsuki results in them hugging you, but then replying a second time with *hugs none* also
![image](https://user-images.githubusercontent.com/42224091/62371311-86583300-b502-11e9-8ab3-35768a9a47f5.png)

**Comment by tangalbert919** [comment]
Such a glorious error made by our own Cheezy. Fixing...

**Comment by tangalbert919** [comment]
Fixed.
