### ISSUE TITLE
Sayori sends message during other dokis conversation

### ISSUE THREAD

**Issue by sayuri3** [sayuri3/dokis#57]
Sayori interrupted during Yuri and Monika interacting, not sure if this is a bug or just chance
![image](https://user-images.githubusercontent.com/42224091/62372906-a25dd380-b506-11e9-9576-065892c7babd.png)

**Comment by tangalbert919** [comment]
This is a bug. We'll work on this.

**Comment by sayuri3** [comment]
> This is a bug. We'll work on this.

Alright, thanks

**Comment by tangalbert919** [comment]
Fixed.
