### ISSUE TITLE
Apply regex to MC

### ISSUE THREAD

**Issue by tangalbert919** [sayuri3/dokis#59]
All of the other dokis have this. Because Cheezy actively refuses to do anything about MC, I'll have to do this.

**Comment by sayuri3** [comment]
I'm not sure what you expected, he actively hates MC, so he just does not do it

**Comment by Cheezy096** [comment]
"he actively hates MC" Really? I thought i left MC so The Weeb didn't break my fucking ears when i did something.

**Comment by Cheezy096** [comment]
Oh welp. Guess i apparently hate MC now.

**Comment by tangalbert919** [comment]
Done. :smile:
