### ISSUE TITLE
Sayori replies with Yuri's response for MC

### ISSUE THREAD

**Issue by sayuri3** [sayuri3/dokis#65]
see attached image
![image](https://user-images.githubusercontent.com/42224091/62395455-44e57900-b53e-11e9-90a3-09250a20f0c5.png)

**Comment by tangalbert919** [comment]
DA FUQ

**Comment by tangalbert919** [comment]
Already fixed in latest commit.

**Comment by sayuri3** [comment]
Alright, thanks
